import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">
          Sorry, nothing here.
        </h1>

        <p>
          Hopefully you will be lucky with
          <br /><br />
          <code>npm run storybook</code>
        </p>
      </main>
    </div>
  )
}

export default Home
